spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoming
    username: root
    password: 123456
  sql:
    init:
      mode: always
  mail:
    protocol: xxx
    host: xxx
    port: xxx
    username: xxx
    password: xxx
